name: CD - Build and Deploy to ECS

on:
  workflow_run:
    workflows: ["CI - Code & Security Analysis"]  # Must match your CI workflow's `name`
    types:
      - completed

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY_URI: ${{ secrets.ECR_REPOSITORY_URI }}
  ECS_CLUSTER: fintech-app-cluster
  ECS_SERVICE: fintech-app-service

jobs:
  deploy:
    name: Build and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t fintech-app ./app
        docker tag fintech-app:latest $ECR_REPOSITORY_URI:latest

    - name: Push Docker image to ECR
      run: |
        docker push $ECR_REPOSITORY_URI:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment
